### ISSUE TITLE
Is it possible to use this code with the u-blox M8N receiver?

### ISSUE THREAD

**Issue by sskarupo** [goGPS-Project/goGPS_Java#29]
Is it possible to use this code with the u-blox M8N receiver? If so, could you please give any instructions -- where to start or anything you would consider relevant?

I'm promarily interested in getting the coordinates, altitude, accuracy and dilution info. From the cursory reading of the manual I know that there is some kind of anti-jamming support, but I'm not sure yet whether it needs to be turned on explicitly; I would also be interested in that, because sometimes I have to deal USB3 interference.

**Comment by ege010** [comment]
The raw data you would need to run goGPS are (at least) pseudoranges of code and phase (i.e. satellite-receiver measured distances) and measurement time.

**Comment by ZiglioUK** [comment]
Happy to report the M8N can provide raw data but at the momento only with firmware 2.01. See:
https://github.com/goGPS-Project/goGPS_Java/blob/master/src/main/java/org/gogpsproject/producer/parser/ublox/DecodeTRKMEAS.java
https://github.com/goGPS-Project/goGPS_Java/blob/master/src/main/java/org/gogpsproject/producer/parser/ublox/DecodeNAVSOL.java

I want to write a little app with the required initialisation sequence but I'm having problems with RXTX and 64bit jvms.
Anyway, you need to enable first the [TRK-MEAS message](http://gpspp.sakura.ne.jp/paper2005/gpssymp_2014_ttaka.pdf):

Text: `!UBX CFG-MSG 3 16 0 1 0 1 0 0` (this doesn't work for me, not sure way)
Hex: `B5 62 06 01 03 00 03 10 01 1E 691 (this one works)

The UBB-NAV-SOL message is also required in order to compute pseudoranges from transmission time.
There might be corrections needed for constellations other than GPS I haven't ported yet from RTK-LIB (the RTKLIB Explorer version, see [here](https://rtklibexplorer.wordpress.com/2016/11/30/pseudorange-corrections-for-the-u-blox-trk-meas-command/) and [here](https://github.com/rtklibexplorer/RTKLIB/blob/da1143ebe8ce9a343dc88f8f826478b699e736e5/src/rcv/ublox.c#L555))

I'm gonna try with the current firmware 3.01 and see what happens.
